<a href="https://colab.research.google.com/github/Lekanggy/Deeplearning-class/blob/master/General.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [2]:
A = torch.arange(6).reshape(-1, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [3]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [10]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = torch.ones(2, 3)
A, B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [12]:
C = B.T + A.T
C

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [18]:
M = torch.arange(24, dtype=float).reshape(2, 3, 4)
M

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]], dtype=torch.float64)

In [20]:
M.shape[2]

4

In [21]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [24]:
#Store the value to avoid memory leakage
x.requires_grad_(True)
x.grad

In [25]:
# Define the equation
y = 2 * torch.dot(x,  x)
y

tensor(28., grad_fn=<MulBackward0>)

In [26]:
#Calclate the gradient(Call the backward function)
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [28]:
#Calculate anotheer gradient
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])